# Generated by Django 5.0.1 on 2024-01-13 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('topic', models.CharField(max_length=20)),
                ('objective', models.CharField(max_length=150)),
                ('theory', models.TextField()),
                ('requirements', models.CharField(max_length=50)),
                ('resources', models.CharField(max_length=50)),
                ('testInitiated', models.BooleanField(default=False)),
                ('testEnded', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sir', to=settings.AUTH_USER_MODEL)),
                ('studentsList', models.ManyToManyField(related_name='performers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
