# Generated by Django 5.0.1 on 2024-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='sectionName',
            field=models.CharField(default='078BCTAB', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labsession',
            name='objective',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
