# Generated by Django 5.0.1 on 2024-01-13 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labify', '0002_labsession_sectionname_alter_labsession_objective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField()),
                ('passedTest', models.BooleanField()),
                ('testMarks', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('initial', models.FileField(default=None, upload_to='pdfs/')),
                ('initialMarks', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exp', to='labify.labsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
