# Generated by Django 5.0.1 on 2024-01-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labify', '0003_studentinlab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='theory',
            field=models.FileField(upload_to='theory/'),
        ),
    ]
