# Generated by Django 5.0.1 on 2024-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labify', '0004_alter_labsession_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='theory',
            field=models.TextField(max_length=700),
        ),
    ]
