# Generated by Django 5.0.1 on 2024-01-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labify', '0005_alter_labsession_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinlab',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentinlab',
            name='passedTest',
            field=models.BooleanField(default=False),
        ),
    ]
